environments:
  - name: env-tg
    path: "environment.yaml"
    variables:
      max_containers: 2
name: other-modules
modules:
  - name: tgpg
    type: postgres
    safety: false
  - name: tgdocdb
    type: aws-documentdb
  - name: tgredishelm
    type: helm-chart
    chart: redis
    chart_version: "15.3.2"
    repository: "https://charts.bitnami.com/bitnami"
  - type: lambda-function
    name: tglambdafunction
    expose_via_domain: true
    filename: ../create-and-destroy-aws/lambda-code/lambda.zip
    runtime: "python3.9"
    handler: "lambda.lambda_handler"
  - type: aws-mysql
    name: tgmysql
    safety: false
  - name: tgredis
    type: redis
    node_type: "cache.t3.micro"
  - name: tgbucket
    type: aws-s3
    bucket_name: "runx-ci-terraform-generated"